*Import census national state and population data, national comes from BEA average of US monthly estimates, states and regions directly from census
clear

import fred B230RC0A052NBEA CAPOP FLPOP TXPOP NYPOP MOPOP COPOP AZPOP NCPOP ILPOP GAPOP NVPOP BEARMPOP ORPOP ALPOP TNPOP MIPOP WIPOP BEASWPOP MNPOP CTPOP HIPOP WAPOP NMPOP OHPOP PAPOP VAPOP IDPOP ARPOP INPOP AKPOP OKPOP SCPOP KSPOP IAPOP UTPOP CNERPOP KYPOP NDPOP LAPOP MAPOP SDPOP NJPOP NEPOP MTPOP WVPOP VTPOP MDPOP MSPOP MEPOP CMWRPOP CSOUPOP WYPOP DCPOP CNEWPOP DEPOP RIPOP NHPOP CMATPOP CWSTPOP BEASEPOP CSATLPOP CPACPOP CENCPOP CMTNPOP BEAGLPOP CESCPOP CWNCPOP CWSCPOP BEANEPOP BEAFWPOP BEAPLPOP BEAMEPOP DSPOP

generate year = substr(datestr,1,4)

*multiply, data is in thousands
foreach var of varlist B230RC0A052NBEA CAPOP FLPOP TXPOP NYPOP MOPOP COPOP AZPOP NCPOP ILPOP GAPOP NVPOP BEARMPOP ORPOP ALPOP TNPOP MIPOP WIPOP BEASWPOP MNPOP CTPOP HIPOP WAPOP NMPOP OHPOP PAPOP VAPOP IDPOP ARPOP INPOP AKPOP OKPOP SCPOP KSPOP IAPOP UTPOP CNERPOP KYPOP NDPOP LAPOP MAPOP SDPOP NJPOP NEPOP MTPOP WVPOP VTPOP MDPOP MSPOP MEPOP CMWRPOP CSOUPOP WYPOP DCPOP CNEWPOP DEPOP RIPOP NHPOP CMATPOP CWSTPOP BEASEPOP CSATLPOP CPACPOP CENCPOP CMTNPOP BEAGLPOP CESCPOP CWNCPOP CWSCPOP BEANEPOP BEAFWPOP BEAPLPOP BEAMEPOP DSPOP{
	replace `var' = `var' * 1000
}

*update most recent data with last available if missing
foreach var of varlist B230RC0A052NBEA CAPOP FLPOP TXPOP NYPOP MOPOP COPOP AZPOP NCPOP ILPOP GAPOP NVPOP BEARMPOP ORPOP ALPOP TNPOP MIPOP WIPOP BEASWPOP MNPOP CTPOP HIPOP WAPOP NMPOP OHPOP PAPOP VAPOP IDPOP ARPOP INPOP AKPOP OKPOP SCPOP KSPOP IAPOP UTPOP CNERPOP KYPOP NDPOP LAPOP MAPOP SDPOP NJPOP NEPOP MTPOP WVPOP VTPOP MDPOP MSPOP MEPOP CMWRPOP CSOUPOP WYPOP DCPOP CNEWPOP DEPOP RIPOP NHPOP CMATPOP CWSTPOP BEASEPOP CSATLPOP CPACPOP CENCPOP CMTNPOP BEAGLPOP CESCPOP CWNCPOP CWSCPOP BEANEPOP BEAFWPOP BEAPLPOP BEAMEPOP DSPOP{
	replace `var' = `var'[_n-1] if missing(`var')
}

export excel using "Data For Tableau.xlsx", firstrow(variables) sheet(Populations, replace)

