*Importy CT GDP by Industry from FRED
clear
set fredkey 440f9bb2021c435e1868fa619b36e5ad

import fred CTRQGSP CTCONSTRQGSP CTMINRQGSP CTUTILRQGSP CTAGRRQGSP CTHLTHSOCASSRQGSP CTEDCATRQGSP CTTRANSWARERQGSP CTMANRQGSP CTRETAILRQGSP CTRERENTLEARQGSP CTPIRQGSP CTACCOMDRQGSP CTOTHSERVERQGSP CTWHOLERQGSP CTINFORQGSP CTADMINWASTRQGSP CTARTENTRECRQGSP CTDURMANRQGSP CTFININSRQGSP CTGOVRQGSP CTMNGCOENTPRRQGSP CTNDURMANRQGSP CTPROBUSRQGSP
























*Importing all states GDP data from FRED
clear
set fredkey 440f9bb2021c435e1868fa619b36e5ad
import fred GDP ALNQGSP AKNQGSP AZNQGSP ARNQGSP CANQGSP CONQGSP CTNQGSP DENQGSP FLNQGSP GANQGSP HINQGSP IDNQGSP ILNQGSP INNQGSP IANQGSP KSNQGSP KYNQGSP LANQGSP MENQGSP MDNQGSP MANQGSP MINQGSP MNNQGSP MSNQGSP MONQGSP MTNQGSP NENQGSP NVNQGSP NHNQGSP NJNQGSP NMNQGSP NYNQGSP NCNQGSP NDNQGSP OHNQGSP OKNQGSP ORNQGSP PANQGSP RINQGSP SCNQGSP SDNQGSP TNNQGSP TXNQGSP UTNQGSP VTNQGSP VANQGSP WANQGSP WVNQGSP WINQGSP WYNQGSP 

rename GDP US_GDP
rename ALNQGSP  AL_GDP
rename AKNQGSP  AK_GDP
rename AZNQGSP  AZ_GDP
rename ARNQGSP  AR_GDP
rename CANQGSP  CA_GDP
rename CONQGSP  CO_GDP
rename CTNQGSP  CT_GDP
rename DENQGSP  DE_GDP
rename FLNQGSP  DC_GDP
rename GANQGSP  FL_GDP
rename HINQGSP  GA_GDP
rename IDNQGSP  HI_GDP
rename ILNQGSP  ID_GDP
rename INNQGSP  IL_GDP
rename IANQGSP  IN_GDP
rename KSNQGSP  IA_GDP
rename KYNQGSP  KS_GDP
rename LANQGSP  KY_GDP
rename MENQGSP  LA_GDP
rename MDNQGSP  ME_GDP
rename MANQGSP  MD_GDP
rename MINQGSP  MA_GDP
rename MNNQGSP  MI_GDP
rename MSNQGSP  MN_GDP
rename MONQGSP  MS_GDP
rename MTNQGSP  MO_GDP
rename NENQGSP  MT_GDP
rename NVNQGSP  NE_GDP
rename NHNQGSP  NV_GDP
rename NJNQGSP  NH_GDP
rename NMNQGSP  NJ_GDP
rename NYNQGSP  NM_GDP
rename NCNQGSP  NY_GDP
rename NDNQGSP  NC_GDP
rename OHNQGSP  ND_GDP
rename OKNQGSP  OH_GDP
rename ORNQGSP  OK_GDP
rename PANQGSP  OR_GDP
rename RINQGSP  PA_GDP
rename SCNQGSP  RI_GDP
rename SDNQGSP  SC_GDP
rename TNNQGSP  SD_GDP
rename TXNQGSP  TN_GDP
rename UTNQGSP  TX_GDP
rename VTNQGSP  UT_GDP
rename VANQGSP  VT_GDP
rename WANQGSP  VA_GDP
rename WVNQGSP  WA_GDP
rename WINQGSP  WV_GDP
rename WYNQGSP  WI_GDP

export excel "Data For Tableau.xlsx", firstrow(variables) sheet("All States Real GDP", replace)

